interface CountryType{
    altSpellings:[],
    area:String,
    borders:[],
    capital:[],
    capitalInfo:{},
    car:{},
    cca2:String,
    cca3:String,
    ccn3:String,
    cioc:String,
    coatOfArms:{},
    continents:[],
    currencies:{},
    demonyms:{},
    fifa:String,
    flag:String,
    flags:{png:string,svg:String,alt:String},
    idd:{root:String,suffixes:any},
    independent:boolean,
    landlocked:boolean,
    languages:[],
    latlng:any,
    maps:{},
    name:{common:String,official:String,nativeName:{eng:{official:String,common:String},mlt:{official:String,common:String}}},
    population:String,
    postalCode:{},
    region:String,
    startOfWeek:String,
    status:String,
    subregion:String,
    timezones:[],
    tld:[],
    translations:{},
    unMember:boolean
}

export default CountryType;